### ISSUE TITLE
Tests fail with spidermonkey==24.2.0-r3

### ISSUE THREAD

**Issue by jamesbroadhead** [doloopwhile/PyExecJS#41]
```
$ python2.7 -V
Python 2.7.10

$ python2.7 test_execjs.py
.............................FE....
======================================================================
ERROR: test_exec (__main__.SpidermonkeyRuntimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_execjs.py", line 41, in test_exec
    self.assertEqual("\u3042", self.runtime.exec_('return "\u3042"'))   # unicode char
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_abstract_runtime.py", line 8, in exec_
    return self._exec_(source, cwd=cwd)
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py", line 47, in _exec_
    return self.Context(self, cwd=cwd).exec_(source)
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py", line 92, in exec_
    return self._extract_result(output)
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py", line 137, in _extract_result
    output = output.decode(self._runtime._encoding)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 8: invalid continuation byte

======================================================================
FAIL: test_eval (__main__.SpidermonkeyRuntimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_execjs.py", line 58, in test_eval
    self.assertEqual("\u3042", self.runtime.eval('"\u3042"'))
AssertionError: u'\u3042' != u'B'
- \u3042
+ B


----------------------------------------------------------------------
Ran 35 tests in 2.629s

FAILED (failures=1, errors=1)
```

```
$ python -V
Python 3.4.3

$ python test_execjs.py
.............................FE.....
======================================================================
ERROR: test_exec (__main__.SpidermonkeyRuntimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_execjs.py", line 41, in test_exec
    self.assertEqual("\u3042", self.runtime.exec_('return "\u3042"'))   # unicode char
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_abstract_runtime.py", line 8, in exec_
    return self._exec_(source, cwd=cwd)
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py", line 47, in _exec_
    return self.Context(self, cwd=cwd).exec_(source)
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py", line 92, in exec_
    return self._extract_result(output)
  File "/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py", line 137, in _extract_result
    output = output.decode(self._runtime._encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 8: invalid continuation byte

======================================================================
FAIL: test_eval (__main__.SpidermonkeyRuntimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_execjs.py", line 58, in test_eval
    self.assertEqual("\u3042", self.runtime.eval('"\u3042"'))
AssertionError: 'あ' != 'B'
- あ
+ B


----------------------------------------------------------------------
Ran 36 tests in 2.692s

FAILED (failures=1, errors=1)
```

```

[I] dev-lang/spidermonkey
     Available versions:
     (0)    1.7.0-r3(0/js) 1.8.5-r4(0/mozjs185) ~1.8.5-r5(0/mozjs185)
     (17)   17.0.0-r4^t
     (24)   24.2.0-r3^t
       {debug icu jit minimal static-libs +system-icu test threadsafe unicode}
     Installed versions:  1.8.5-r4(13:20:01 09/12/15)(-debug -minimal -static-libs -test) 24.2.0-r3(24)(14:46:00 10/12/15)(system-icu -debug -icu -jit -minimal -static-libs -test)
     Homepage:            http://www.mozilla.org/js/spidermonkey/
     Description:         Stand-alone JavaScript C library
```

**Comment by doloopwhile** [comment]
It looks a encoding problem.
Will you tell me your environment vairables such as `$LANG`.

**Comment by jamesbroadhead** [comment]
```

$ locale
LANG=en_IE.utf8
LC_CTYPE="en_IE.utf8"
LC_NUMERIC="en_IE.utf8"
LC_TIME="en_IE.utf8"
LC_COLLATE="en_IE.utf8"
LC_MONETARY="en_IE.utf8"
LC_MESSAGES="en_IE.utf8"
LC_PAPER="en_IE.utf8"
LC_NAME="en_IE.utf8"
LC_ADDRESS="en_IE.utf8"
LC_TELEPHONE="en_IE.utf8"
LC_MEASUREMENT="en_IE.utf8"
LC_IDENTIFICATION="en_IE.utf8"
LC_ALL=
```

**Comment by doloopwhile** [comment]
Sorry, I am not able to reproduce the error.
