### ISSUE TITLE
Print available runtimes doesn't work.

### ISSUE THREAD

**Issue by criccomini** [doloopwhile/PyExecJS#45]
Print available runtimes doesn't work.

```
$ python --version
Python 2.7.6

$ python -m execjs --print-available-runtimes
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chrisr/.virtual-env/asdf/lib/python2.7/site-packages/execjs/__main__.py", line 57, in <module>
    main()
  File "/Users/chrisr/.virtual-env/asdf/lib/python2.7/site-packages/execjs/__main__.py", line 36, in main
    opts = parser.parse_args()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1926, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1866, in consume_optional
    take_action(action, args, option_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1794, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/chrisr/.virtual-env/asdf/lib/python2.7/site-packages/execjs/__main__.py", line 24, in __call__
    buffer.write(name + "\n")
TypeError: unicode argument expected, got 'str'

$ pip freeze | grep PyExec
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
PyExecJS==1.3.0
```

**Comment by criccomini** [comment]
This seems to fix it:

                buffer.write(unicode(name + "\n"))

**Comment by doloopwhile** [comment]
I fix the bug. Thanks.
