### ISSUE TITLE
module 'execjs' has no attribute 'RuntimeUnavailable'

### ISSUE THREAD

**Issue by criccomini** [doloopwhile/PyExecJS#46]
Got this when running on a system that has no runtimes. Seems like the RuntimeUnavailable exception is missing.

```
[tests.udfs.test_el.TestElUdf.setup] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/local/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python3.5/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python3.5/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/var/asdf/tests/udfs/test_el.py", line 13, in setUpClass
    cls.exact_row_match_udf = UdfTestHarness('el.js', 'exact_row_match')
  File "/var/asdf/tests/udfs/helper_udfs.py", line 34, in __init__
    self.udf = execjs.compile(self.udf_str)
  File "/usr/local/lib/python3.5/site-packages/execjs/__init__.py", line 69, in compile
    return get().compile(source)
  File "/usr/local/lib/python3.5/site-packages/execjs/_runtimes.py", line 24, in get
    return _auto_detect()
  File "/usr/local/lib/python3.5/site-packages/execjs/_runtimes.py", line 56, in _auto_detect
    raise execjs.RuntimeUnavailable("Could not find a JavaScript runtime.")
AttributeError: module 'execjs' has no attribute 'RuntimeUnavailable'
```

**Comment by doloopwhile** [comment]
The line `raise execjs.RuntimeUnavailable("Could not find a JavaScript runtime.")` is not found in `master` branch.

Please checkout `master` branch or latest release `v1.3.0`.
