### ISSUE TITLE
import execjs fails with AttributeError

### ISSUE THREAD

**Issue by maxpmaxp** [doloopwhile/PyExecJS#49]
I have Python 2.7, PyExecJS-1.3.1, PhantomJS 2.1.1.
```
>>> import execjs
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../PyExecJS-1.3.1-py2.7.egg/execjs/__init__.py", line 26, in <module>
    import execjs._runtimes
  File "/...egg/execjs/_runtimes.py", line 8, in <module>
    import execjs._external_runtime as external_runtime
  File "/.../PyExecJS-1.3.1-py2.7.egg/execjs/_external_runtime.py", line 15, in <module>
    from execjs._abstract_runtime import AbstractRuntime
  File "/.../PyExecJS-1.3.1-py2.7.egg/execjs/_abstract_runtime.py", line 6, in <module>
    @six.add_metaclass(ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'
```

If I set `EXECJS_RUNTIME` explicitly to 'PhantomJS' the import fails with another `AttributeError`

```
>>> import os
>>> os.environ["EXECJS_RUNTIME"] = "PhantomJS"
>>> import execjs
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../PyExecJS-1.3.1-py2.7.egg/execjs/__init__.py", line 26, in <module>
    import execjs._runtimes
  File "/.../execjs/_runtimes.py", line 8, in <module>
    import execjs._external_runtime as external_runtime
  File "/.../PyExecJS-1.3.1-py2.7.egg/execjs/_external_runtime.py", line 12, in <module>
    import execjs._json2 as _json2
AttributeError: 'module' object has no attribute '_json2'
```

**Comment by doloopwhile** [comment]
First error is because `six` version is different. It was fixed.

Second error does not occur in my environment. It seems that sources are not correctly checked out.

Thanks.
